packages:
  - apps/*
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - scripts/*
  - services/*

linkWorkspacePackages: true

ignoredBuiltDependencies:
  - unrs-resolver
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - vue-demi
