packages:
  - apps/*
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - scripts/*

ignoredBuiltDependencies:
  - unrs-resolver

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - vue-demi
